// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ecdh_aead.proto

package ecdh_aead_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common_go_proto "github.com/google/tink/go/proto/common_go_proto"
	tink_go_proto "github.com/google/tink/go/proto/tink_go_proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyType int32

const (
	KeyType_UNKNOWN_KEY_TYPE KeyType = 0
	KeyType_EC               KeyType = 1
	KeyType_OKP              KeyType = 2
)

var KeyType_name = map[int32]string{
	0: "UNKNOWN_KEY_TYPE",
	1: "EC",
	2: "OKP",
}

var KeyType_value = map[string]int32{
	"UNKNOWN_KEY_TYPE": 0,
	"EC":               1,
	"OKP":              2,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{0}
}

type EcdhKwParams struct {
	CurveType            common_go_proto.EllipticCurveType `protobuf:"varint,1,opt,name=curve_type,json=curveType,proto3,enum=google.crypto.tink.EllipticCurveType" json:"curve_type,omitempty"`
	KeyType              KeyType                           `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=google.crypto.tink.KeyType" json:"key_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *EcdhKwParams) Reset()         { *m = EcdhKwParams{} }
func (m *EcdhKwParams) String() string { return proto.CompactTextString(m) }
func (*EcdhKwParams) ProtoMessage()    {}
func (*EcdhKwParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{0}
}

func (m *EcdhKwParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhKwParams.Unmarshal(m, b)
}
func (m *EcdhKwParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhKwParams.Marshal(b, m, deterministic)
}
func (m *EcdhKwParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhKwParams.Merge(m, src)
}
func (m *EcdhKwParams) XXX_Size() int {
	return xxx_messageInfo_EcdhKwParams.Size(m)
}
func (m *EcdhKwParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhKwParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhKwParams proto.InternalMessageInfo

func (m *EcdhKwParams) GetCurveType() common_go_proto.EllipticCurveType {
	if m != nil {
		return m.CurveType
	}
	return common_go_proto.EllipticCurveType_UNKNOWN_CURVE
}

func (m *EcdhKwParams) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KeyType_UNKNOWN_KEY_TYPE
}

type EcdhAeadEncParams struct {
	AeadEnc              *tink_go_proto.KeyTemplate `protobuf:"bytes,1,opt,name=aead_enc,json=aeadEnc,proto3" json:"aead_enc,omitempty"`
	CEK                  []byte                     `protobuf:"bytes,2,opt,name=CEK,proto3" json:"CEK,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EcdhAeadEncParams) Reset()         { *m = EcdhAeadEncParams{} }
func (m *EcdhAeadEncParams) String() string { return proto.CompactTextString(m) }
func (*EcdhAeadEncParams) ProtoMessage()    {}
func (*EcdhAeadEncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{1}
}

func (m *EcdhAeadEncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhAeadEncParams.Unmarshal(m, b)
}
func (m *EcdhAeadEncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhAeadEncParams.Marshal(b, m, deterministic)
}
func (m *EcdhAeadEncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhAeadEncParams.Merge(m, src)
}
func (m *EcdhAeadEncParams) XXX_Size() int {
	return xxx_messageInfo_EcdhAeadEncParams.Size(m)
}
func (m *EcdhAeadEncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhAeadEncParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhAeadEncParams proto.InternalMessageInfo

func (m *EcdhAeadEncParams) GetAeadEnc() *tink_go_proto.KeyTemplate {
	if m != nil {
		return m.AeadEnc
	}
	return nil
}

func (m *EcdhAeadEncParams) GetCEK() []byte {
	if m != nil {
		return m.CEK
	}
	return nil
}

type EcdhAeadParams struct {
	KwParams             *EcdhKwParams                 `protobuf:"bytes,1,opt,name=kw_params,json=kwParams,proto3" json:"kw_params,omitempty"`
	EncParams            *EcdhAeadEncParams            `protobuf:"bytes,2,opt,name=enc_params,json=encParams,proto3" json:"enc_params,omitempty"`
	EcPointFormat        common_go_proto.EcPointFormat `protobuf:"varint,3,opt,name=ec_point_format,json=ecPointFormat,proto3,enum=google.crypto.tink.EcPointFormat" json:"ec_point_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EcdhAeadParams) Reset()         { *m = EcdhAeadParams{} }
func (m *EcdhAeadParams) String() string { return proto.CompactTextString(m) }
func (*EcdhAeadParams) ProtoMessage()    {}
func (*EcdhAeadParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{2}
}

func (m *EcdhAeadParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhAeadParams.Unmarshal(m, b)
}
func (m *EcdhAeadParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhAeadParams.Marshal(b, m, deterministic)
}
func (m *EcdhAeadParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhAeadParams.Merge(m, src)
}
func (m *EcdhAeadParams) XXX_Size() int {
	return xxx_messageInfo_EcdhAeadParams.Size(m)
}
func (m *EcdhAeadParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhAeadParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhAeadParams proto.InternalMessageInfo

func (m *EcdhAeadParams) GetKwParams() *EcdhKwParams {
	if m != nil {
		return m.KwParams
	}
	return nil
}

func (m *EcdhAeadParams) GetEncParams() *EcdhAeadEncParams {
	if m != nil {
		return m.EncParams
	}
	return nil
}

func (m *EcdhAeadParams) GetEcPointFormat() common_go_proto.EcPointFormat {
	if m != nil {
		return m.EcPointFormat
	}
	return common_go_proto.EcPointFormat_UNKNOWN_FORMAT
}

type EcdhAeadPublicKey struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params               *EcdhAeadParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	KID                  string          `protobuf:"bytes,3,opt,name=KID,proto3" json:"KID,omitempty"`
	X                    []byte          `protobuf:"bytes,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte          `protobuf:"bytes,5,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EcdhAeadPublicKey) Reset()         { *m = EcdhAeadPublicKey{} }
func (m *EcdhAeadPublicKey) String() string { return proto.CompactTextString(m) }
func (*EcdhAeadPublicKey) ProtoMessage()    {}
func (*EcdhAeadPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{3}
}

func (m *EcdhAeadPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhAeadPublicKey.Unmarshal(m, b)
}
func (m *EcdhAeadPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhAeadPublicKey.Marshal(b, m, deterministic)
}
func (m *EcdhAeadPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhAeadPublicKey.Merge(m, src)
}
func (m *EcdhAeadPublicKey) XXX_Size() int {
	return xxx_messageInfo_EcdhAeadPublicKey.Size(m)
}
func (m *EcdhAeadPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhAeadPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhAeadPublicKey proto.InternalMessageInfo

func (m *EcdhAeadPublicKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EcdhAeadPublicKey) GetParams() *EcdhAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *EcdhAeadPublicKey) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func (m *EcdhAeadPublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *EcdhAeadPublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type EcdhAeadPrivateKey struct {
	Version              uint32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublicKey            *EcdhAeadPublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyValue             []byte             `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EcdhAeadPrivateKey) Reset()         { *m = EcdhAeadPrivateKey{} }
func (m *EcdhAeadPrivateKey) String() string { return proto.CompactTextString(m) }
func (*EcdhAeadPrivateKey) ProtoMessage()    {}
func (*EcdhAeadPrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{4}
}

func (m *EcdhAeadPrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhAeadPrivateKey.Unmarshal(m, b)
}
func (m *EcdhAeadPrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhAeadPrivateKey.Marshal(b, m, deterministic)
}
func (m *EcdhAeadPrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhAeadPrivateKey.Merge(m, src)
}
func (m *EcdhAeadPrivateKey) XXX_Size() int {
	return xxx_messageInfo_EcdhAeadPrivateKey.Size(m)
}
func (m *EcdhAeadPrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhAeadPrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhAeadPrivateKey proto.InternalMessageInfo

func (m *EcdhAeadPrivateKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EcdhAeadPrivateKey) GetPublicKey() *EcdhAeadPublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *EcdhAeadPrivateKey) GetKeyValue() []byte {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type EcdhAeadKeyFormat struct {
	Params               *EcdhAeadParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EcdhAeadKeyFormat) Reset()         { *m = EcdhAeadKeyFormat{} }
func (m *EcdhAeadKeyFormat) String() string { return proto.CompactTextString(m) }
func (*EcdhAeadKeyFormat) ProtoMessage()    {}
func (*EcdhAeadKeyFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f9291a7083da43, []int{5}
}

func (m *EcdhAeadKeyFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhAeadKeyFormat.Unmarshal(m, b)
}
func (m *EcdhAeadKeyFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhAeadKeyFormat.Marshal(b, m, deterministic)
}
func (m *EcdhAeadKeyFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhAeadKeyFormat.Merge(m, src)
}
func (m *EcdhAeadKeyFormat) XXX_Size() int {
	return xxx_messageInfo_EcdhAeadKeyFormat.Size(m)
}
func (m *EcdhAeadKeyFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhAeadKeyFormat.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhAeadKeyFormat proto.InternalMessageInfo

func (m *EcdhAeadKeyFormat) GetParams() *EcdhAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.crypto.tink.KeyType", KeyType_name, KeyType_value)
	proto.RegisterType((*EcdhKwParams)(nil), "google.crypto.tink.EcdhKwParams")
	proto.RegisterType((*EcdhAeadEncParams)(nil), "google.crypto.tink.EcdhAeadEncParams")
	proto.RegisterType((*EcdhAeadParams)(nil), "google.crypto.tink.EcdhAeadParams")
	proto.RegisterType((*EcdhAeadPublicKey)(nil), "google.crypto.tink.EcdhAeadPublicKey")
	proto.RegisterType((*EcdhAeadPrivateKey)(nil), "google.crypto.tink.EcdhAeadPrivateKey")
	proto.RegisterType((*EcdhAeadKeyFormat)(nil), "google.crypto.tink.EcdhAeadKeyFormat")
}

func init() { proto.RegisterFile("proto/ecdh_aead.proto", fileDescriptor_62f9291a7083da43) }

var fileDescriptor_62f9291a7083da43 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6b, 0x13, 0x4f,
	0x14, 0xfd, 0x4d, 0xfa, 0x33, 0xe9, 0x8e, 0x69, 0x5d, 0x07, 0x85, 0xd0, 0x0a, 0xd6, 0x85, 0x82,
	0x08, 0xdd, 0x48, 0x05, 0x1f, 0x0a, 0x3e, 0xd8, 0x76, 0x85, 0xb0, 0x90, 0x2c, 0x4b, 0x54, 0xea,
	0x83, 0xcb, 0x64, 0x72, 0xbb, 0x19, 0xf6, 0xcf, 0x0c, 0x93, 0x4d, 0xd2, 0xfd, 0x08, 0x82, 0x2f,
	0x3e, 0xf9, 0xee, 0x27, 0xf3, 0xa3, 0xc8, 0xcc, 0x6e, 0xd2, 0x54, 0xd3, 0xa2, 0x6f, 0xf7, 0xcc,
	0xde, 0x7b, 0xee, 0x39, 0x87, 0x99, 0xc5, 0x8f, 0xa5, 0x12, 0x85, 0xe8, 0x02, 0x1b, 0x4f, 0x22,
	0x0a, 0x74, 0xec, 0x1a, 0x4c, 0x48, 0x2c, 0x44, 0x9c, 0x82, 0xcb, 0x54, 0x29, 0x0b, 0xe1, 0x16,
	0x3c, 0x4f, 0xf6, 0x48, 0xd5, 0xca, 0x44, 0x96, 0x89, 0xbc, 0xea, 0xdb, 0xb3, 0xab, 0x33, 0xfd,
	0xbd, 0x3a, 0x71, 0xbe, 0x22, 0xdc, 0xf6, 0xd8, 0x78, 0xe2, 0x2f, 0x02, 0xaa, 0x68, 0x36, 0x25,
	0xe7, 0x18, 0xb3, 0x99, 0x9a, 0x43, 0x54, 0x94, 0x12, 0x3a, 0xe8, 0x00, 0x3d, 0xdf, 0x3d, 0x3e,
	0x74, 0xff, 0xe4, 0x77, 0xbd, 0x34, 0xe5, 0xb2, 0xe0, 0xec, 0x4c, 0x77, 0x0f, 0x4b, 0x09, 0xa1,
	0xc5, 0x96, 0x25, 0x79, 0x8d, 0xb7, 0x13, 0x28, 0x2b, 0x8e, 0x86, 0xe1, 0xd8, 0xdf, 0xc4, 0xe1,
	0x43, 0x69, 0x26, 0x5b, 0x49, 0x55, 0x38, 0x14, 0x3f, 0xd4, 0x6a, 0xde, 0x02, 0x1d, 0x7b, 0x39,
	0xab, 0x25, 0x9d, 0xe0, 0x6d, 0xed, 0x35, 0x82, 0x9c, 0x19, 0x41, 0xf7, 0x8f, 0x9f, 0xde, 0x46,
	0x06, 0x99, 0x4c, 0x69, 0x01, 0x61, 0x8b, 0x56, 0x0c, 0xc4, 0xc6, 0x5b, 0x67, 0x9e, 0x6f, 0x34,
	0xb4, 0x43, 0x5d, 0x3a, 0x3f, 0x11, 0xde, 0x5d, 0xee, 0xa8, 0x17, 0xbc, 0xc1, 0x56, 0xb2, 0x88,
	0xa4, 0x01, 0xf5, 0x86, 0x83, 0x8d, 0x96, 0xd7, 0x82, 0x0a, 0xb7, 0x93, 0xb5, 0xc8, 0x20, 0x67,
	0xcb, 0xf9, 0x86, 0x99, 0x3f, 0xbc, 0x6d, 0xfe, 0x86, 0xb5, 0xd0, 0x82, 0x95, 0xcb, 0x1e, 0x7e,
	0x00, 0x2c, 0x92, 0x82, 0xe7, 0x45, 0x74, 0x29, 0x54, 0x46, 0x8b, 0xce, 0x96, 0x49, 0xee, 0xd9,
	0x66, 0xaa, 0x40, 0x77, 0xbe, 0x33, 0x8d, 0xe1, 0x0e, 0xac, 0x43, 0xe7, 0x3b, 0xba, 0x8e, 0x31,
	0x98, 0x8d, 0x52, 0xce, 0x7c, 0x28, 0x49, 0x07, 0xb7, 0xe6, 0xa0, 0xa6, 0x5c, 0xe4, 0xc6, 0xe3,
	0x4e, 0xb8, 0x84, 0xe4, 0x04, 0x37, 0x6f, 0x88, 0x77, 0xee, 0x12, 0x5f, 0x2b, 0xaf, 0x27, 0x74,
	0xc0, 0x7e, 0xef, 0xdc, 0x48, 0xb5, 0x42, 0x5d, 0x92, 0x36, 0x46, 0x57, 0x9d, 0xff, 0x4d, 0xe0,
	0xe8, 0x4a, 0xa3, 0xb2, 0x73, 0xaf, 0x42, 0xa5, 0xf3, 0x0d, 0x61, 0xb2, 0x22, 0x52, 0x7c, 0x4e,
	0x0b, 0xb8, 0x5b, 0xda, 0x39, 0xc6, 0xd2, 0x38, 0x88, 0x12, 0x28, 0xff, 0x26, 0xdb, 0x95, 0xdf,
	0xd0, 0x92, 0x2b, 0xeb, 0xfb, 0xd8, 0xd2, 0xd7, 0x71, 0x4e, 0xd3, 0x19, 0x18, 0xa9, 0xed, 0x50,
	0xdf, 0xcf, 0x0f, 0x1a, 0x3b, 0x83, 0xeb, 0xb0, 0x7c, 0x28, 0xab, 0x08, 0xd7, 0x22, 0x41, 0xff,
	0x1a, 0xc9, 0x8b, 0x97, 0xb8, 0x55, 0x5f, 0x6c, 0xf2, 0x08, 0xdb, 0xef, 0xfb, 0x7e, 0x7f, 0xf0,
	0xb1, 0x1f, 0xf9, 0xde, 0x45, 0x34, 0xbc, 0x08, 0x3c, 0xfb, 0x3f, 0xd2, 0xc4, 0x0d, 0xef, 0xcc,
	0x46, 0xa4, 0x85, 0xb7, 0x06, 0x7e, 0x60, 0x37, 0x4e, 0xbf, 0x20, 0xfc, 0x84, 0x89, 0x6c, 0xd3,
	0x0e, 0xf3, 0x4c, 0x03, 0xf4, 0xe9, 0x73, 0xcc, 0x8b, 0xc9, 0x6c, 0xe4, 0x32, 0x91, 0x75, 0x27,
	0xa5, 0x04, 0x95, 0xc2, 0x38, 0x06, 0xd5, 0xa5, 0x8a, 0xc3, 0xf4, 0xe8, 0x52, 0xd1, 0x0c, 0x16,
	0x42, 0x25, 0x47, 0xb1, 0xe8, 0x56, 0xe3, 0xe6, 0x95, 0xd7, 0xa5, 0x54, 0x3c, 0xe3, 0x05, 0x9f,
	0x43, 0xf7, 0xb7, 0xff, 0x47, 0x14, 0x8b, 0xc8, 0x1c, 0xfd, 0x68, 0x34, 0x87, 0xbd, 0xbe, 0x1f,
	0x9c, 0x8e, 0x9a, 0x06, 0xbf, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x60, 0x55, 0xe5, 0xf0, 0x6b,
	0x04, 0x00, 0x00,
}
