# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

# TODO: Disable CircleCI builds

version: 2

jobs:
  noop:
    docker:
      - image: circleci/golang:1.13
    steps:
      - run: exit
workflows:
  version: 2
  noop:
    jobs:
      - noop
