// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/tink/ecdhes_aead.proto

package ecdhes_aead_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common_composite_go_proto "github.com/hyperledger/aries-framework-go/pkg/crypto/tinkcrypto/primitive/proto/common_composite_go_proto"
	common_go_proto "github.com/google/tink/go/proto/common_go_proto"
	tink_go_proto "github.com/google/tink/go/proto/tink_go_proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EcdhesKwParams struct {
	CurveType            common_go_proto.EllipticCurveType        `protobuf:"varint,1,opt,name=curve_type,json=curveType,proto3,enum=google.crypto.tink.EllipticCurveType" json:"curve_type,omitempty"`
	KeyType              common_composite_go_proto.KeyType        `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=google.crypto.tink.KeyType" json:"key_type,omitempty"`
	Recipients           []*common_composite_go_proto.ECPublicKey `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *EcdhesKwParams) Reset()         { *m = EcdhesKwParams{} }
func (m *EcdhesKwParams) String() string { return proto.CompactTextString(m) }
func (*EcdhesKwParams) ProtoMessage()    {}
func (*EcdhesKwParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{0}
}

func (m *EcdhesKwParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesKwParams.Unmarshal(m, b)
}
func (m *EcdhesKwParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesKwParams.Marshal(b, m, deterministic)
}
func (m *EcdhesKwParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesKwParams.Merge(m, src)
}
func (m *EcdhesKwParams) XXX_Size() int {
	return xxx_messageInfo_EcdhesKwParams.Size(m)
}
func (m *EcdhesKwParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesKwParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesKwParams proto.InternalMessageInfo

func (m *EcdhesKwParams) GetCurveType() common_go_proto.EllipticCurveType {
	if m != nil {
		return m.CurveType
	}
	return common_go_proto.EllipticCurveType_UNKNOWN_CURVE
}

func (m *EcdhesKwParams) GetKeyType() common_composite_go_proto.KeyType {
	if m != nil {
		return m.KeyType
	}
	return common_composite_go_proto.KeyType_UNKNOWN_KEY_TYPE
}

func (m *EcdhesKwParams) GetRecipients() []*common_composite_go_proto.ECPublicKey {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type EcdhesAeadEncParams struct {
	AeadEnc              *tink_go_proto.KeyTemplate `protobuf:"bytes,1,opt,name=aead_enc,json=aeadEnc,proto3" json:"aead_enc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EcdhesAeadEncParams) Reset()         { *m = EcdhesAeadEncParams{} }
func (m *EcdhesAeadEncParams) String() string { return proto.CompactTextString(m) }
func (*EcdhesAeadEncParams) ProtoMessage()    {}
func (*EcdhesAeadEncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{1}
}

func (m *EcdhesAeadEncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesAeadEncParams.Unmarshal(m, b)
}
func (m *EcdhesAeadEncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesAeadEncParams.Marshal(b, m, deterministic)
}
func (m *EcdhesAeadEncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesAeadEncParams.Merge(m, src)
}
func (m *EcdhesAeadEncParams) XXX_Size() int {
	return xxx_messageInfo_EcdhesAeadEncParams.Size(m)
}
func (m *EcdhesAeadEncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesAeadEncParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesAeadEncParams proto.InternalMessageInfo

func (m *EcdhesAeadEncParams) GetAeadEnc() *tink_go_proto.KeyTemplate {
	if m != nil {
		return m.AeadEnc
	}
	return nil
}

type EcdhesAeadParams struct {
	KwParams             *EcdhesKwParams               `protobuf:"bytes,1,opt,name=kw_params,json=kwParams,proto3" json:"kw_params,omitempty"`
	EncParams            *EcdhesAeadEncParams          `protobuf:"bytes,2,opt,name=enc_params,json=encParams,proto3" json:"enc_params,omitempty"`
	EcPointFormat        common_go_proto.EcPointFormat `protobuf:"varint,3,opt,name=ec_point_format,json=ecPointFormat,proto3,enum=google.crypto.tink.EcPointFormat" json:"ec_point_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *EcdhesAeadParams) Reset()         { *m = EcdhesAeadParams{} }
func (m *EcdhesAeadParams) String() string { return proto.CompactTextString(m) }
func (*EcdhesAeadParams) ProtoMessage()    {}
func (*EcdhesAeadParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{2}
}

func (m *EcdhesAeadParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesAeadParams.Unmarshal(m, b)
}
func (m *EcdhesAeadParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesAeadParams.Marshal(b, m, deterministic)
}
func (m *EcdhesAeadParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesAeadParams.Merge(m, src)
}
func (m *EcdhesAeadParams) XXX_Size() int {
	return xxx_messageInfo_EcdhesAeadParams.Size(m)
}
func (m *EcdhesAeadParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesAeadParams.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesAeadParams proto.InternalMessageInfo

func (m *EcdhesAeadParams) GetKwParams() *EcdhesKwParams {
	if m != nil {
		return m.KwParams
	}
	return nil
}

func (m *EcdhesAeadParams) GetEncParams() *EcdhesAeadEncParams {
	if m != nil {
		return m.EncParams
	}
	return nil
}

func (m *EcdhesAeadParams) GetEcPointFormat() common_go_proto.EcPointFormat {
	if m != nil {
		return m.EcPointFormat
	}
	return common_go_proto.EcPointFormat_UNKNOWN_FORMAT
}

type EcdhesAeadPublicKey struct {
	Version              uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params               *EcdhesAeadParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	KID                  string            `protobuf:"bytes,3,opt,name=KID,proto3" json:"KID,omitempty"`
	X                    []byte            `protobuf:"bytes,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte            `protobuf:"bytes,5,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EcdhesAeadPublicKey) Reset()         { *m = EcdhesAeadPublicKey{} }
func (m *EcdhesAeadPublicKey) String() string { return proto.CompactTextString(m) }
func (*EcdhesAeadPublicKey) ProtoMessage()    {}
func (*EcdhesAeadPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{3}
}

func (m *EcdhesAeadPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesAeadPublicKey.Unmarshal(m, b)
}
func (m *EcdhesAeadPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesAeadPublicKey.Marshal(b, m, deterministic)
}
func (m *EcdhesAeadPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesAeadPublicKey.Merge(m, src)
}
func (m *EcdhesAeadPublicKey) XXX_Size() int {
	return xxx_messageInfo_EcdhesAeadPublicKey.Size(m)
}
func (m *EcdhesAeadPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesAeadPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesAeadPublicKey proto.InternalMessageInfo

func (m *EcdhesAeadPublicKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EcdhesAeadPublicKey) GetParams() *EcdhesAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *EcdhesAeadPublicKey) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func (m *EcdhesAeadPublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *EcdhesAeadPublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type EcdhesAeadPrivateKey struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublicKey            *EcdhesAeadPublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyValue             []byte               `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EcdhesAeadPrivateKey) Reset()         { *m = EcdhesAeadPrivateKey{} }
func (m *EcdhesAeadPrivateKey) String() string { return proto.CompactTextString(m) }
func (*EcdhesAeadPrivateKey) ProtoMessage()    {}
func (*EcdhesAeadPrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{4}
}

func (m *EcdhesAeadPrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesAeadPrivateKey.Unmarshal(m, b)
}
func (m *EcdhesAeadPrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesAeadPrivateKey.Marshal(b, m, deterministic)
}
func (m *EcdhesAeadPrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesAeadPrivateKey.Merge(m, src)
}
func (m *EcdhesAeadPrivateKey) XXX_Size() int {
	return xxx_messageInfo_EcdhesAeadPrivateKey.Size(m)
}
func (m *EcdhesAeadPrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesAeadPrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesAeadPrivateKey proto.InternalMessageInfo

func (m *EcdhesAeadPrivateKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EcdhesAeadPrivateKey) GetPublicKey() *EcdhesAeadPublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *EcdhesAeadPrivateKey) GetKeyValue() []byte {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type EcdhesAeadKeyFormat struct {
	Params               *EcdhesAeadParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EcdhesAeadKeyFormat) Reset()         { *m = EcdhesAeadKeyFormat{} }
func (m *EcdhesAeadKeyFormat) String() string { return proto.CompactTextString(m) }
func (*EcdhesAeadKeyFormat) ProtoMessage()    {}
func (*EcdhesAeadKeyFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_59a984bc83da313d, []int{5}
}

func (m *EcdhesAeadKeyFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EcdhesAeadKeyFormat.Unmarshal(m, b)
}
func (m *EcdhesAeadKeyFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EcdhesAeadKeyFormat.Marshal(b, m, deterministic)
}
func (m *EcdhesAeadKeyFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EcdhesAeadKeyFormat.Merge(m, src)
}
func (m *EcdhesAeadKeyFormat) XXX_Size() int {
	return xxx_messageInfo_EcdhesAeadKeyFormat.Size(m)
}
func (m *EcdhesAeadKeyFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_EcdhesAeadKeyFormat.DiscardUnknown(m)
}

var xxx_messageInfo_EcdhesAeadKeyFormat proto.InternalMessageInfo

func (m *EcdhesAeadKeyFormat) GetParams() *EcdhesAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*EcdhesKwParams)(nil), "google.crypto.tink.EcdhesKwParams")
	proto.RegisterType((*EcdhesAeadEncParams)(nil), "google.crypto.tink.EcdhesAeadEncParams")
	proto.RegisterType((*EcdhesAeadParams)(nil), "google.crypto.tink.EcdhesAeadParams")
	proto.RegisterType((*EcdhesAeadPublicKey)(nil), "google.crypto.tink.EcdhesAeadPublicKey")
	proto.RegisterType((*EcdhesAeadPrivateKey)(nil), "google.crypto.tink.EcdhesAeadPrivateKey")
	proto.RegisterType((*EcdhesAeadKeyFormat)(nil), "google.crypto.tink.EcdhesAeadKeyFormat")
}

func init() { proto.RegisterFile("proto/ecdhes_aead.proto", fileDescriptor_59a984bc83da313d) }

var fileDescriptor_59a984bc83da313d = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0x0d, 0xb4, 0xf5, 0xd0, 0x96, 0xca, 0x20, 0x61, 0xb5, 0x95, 0x08, 0x16, 0x88,
	0x5c, 0xea, 0x48, 0x45, 0xe2, 0x80, 0x90, 0x2a, 0xda, 0x26, 0x52, 0x64, 0x09, 0x05, 0x53, 0x71,
	0xe0, 0x62, 0x36, 0x9b, 0xa9, 0xb3, 0xf2, 0x9f, 0x5d, 0xad, 0x37, 0x49, 0xfd, 0x0c, 0x9c, 0x39,
	0x71, 0xe3, 0x85, 0x78, 0x0b, 0x9e, 0x03, 0x79, 0xed, 0xa4, 0x8e, 0x9a, 0x56, 0x70, 0x9b, 0x19,
	0xcf, 0xfc, 0x76, 0xbe, 0x4f, 0xeb, 0x85, 0x67, 0x52, 0x09, 0x2d, 0xba, 0xc8, 0xc6, 0x13, 0xcc,
	0x43, 0x8a, 0x74, 0xec, 0x99, 0x8a, 0x6d, 0x47, 0x42, 0x44, 0x09, 0x7a, 0x4c, 0x15, 0x52, 0x0b,
	0x4f, 0xf3, 0x2c, 0x3e, 0xb0, 0xab, 0x66, 0x26, 0xd2, 0x54, 0x64, 0x55, 0xdf, 0xc1, 0x7e, 0x55,
	0x2b, 0xbf, 0xd7, 0x95, 0xa3, 0x66, 0x57, 0xc8, 0x44, 0x2a, 0x45, 0xce, 0x35, 0x56, 0x5f, 0xdd,
	0xdf, 0x04, 0xf6, 0x7a, 0xe6, 0x34, 0x7f, 0x3e, 0xa4, 0x8a, 0xa6, 0xb9, 0x7d, 0x01, 0xc0, 0xa6,
	0x6a, 0x86, 0xa1, 0x2e, 0x24, 0x3a, 0xa4, 0x4d, 0x3a, 0x7b, 0x27, 0xaf, 0xbc, 0xdb, 0xe7, 0x7b,
	0xbd, 0x24, 0xe1, 0x52, 0x73, 0x76, 0x5e, 0x76, 0x5f, 0x16, 0x12, 0x03, 0x8b, 0x2d, 0x42, 0xfb,
	0x2d, 0x6c, 0xc7, 0x58, 0x54, 0x8c, 0x0d, 0xc3, 0x38, 0x5c, 0xc7, 0xf0, 0xb1, 0x30, 0x93, 0x5b,
	0x71, 0x15, 0xd8, 0xa7, 0x00, 0x0a, 0x19, 0x97, 0x1c, 0x33, 0x9d, 0x3b, 0xad, 0x76, 0xab, 0xf3,
	0xe8, 0xe4, 0xf9, 0xda, 0xd3, 0xcf, 0x87, 0xd3, 0x51, 0xc2, 0x99, 0x8f, 0x45, 0xd0, 0x18, 0x71,
	0x3f, 0xc1, 0x93, 0x4a, 0xd0, 0x07, 0xa4, 0xe3, 0x5e, 0xc6, 0x6a, 0x55, 0xef, 0x60, 0xbb, 0xb4,
	0x33, 0xc4, 0x8c, 0x19, 0x4d, 0x77, 0x50, 0xcb, 0x7d, 0x30, 0x95, 0x09, 0xd5, 0x18, 0x6c, 0xd1,
	0x8a, 0xe0, 0xfe, 0x21, 0xb0, 0x7f, 0xc3, 0xac, 0x81, 0xa7, 0x60, 0xc5, 0xf3, 0x50, 0x9a, 0xa4,
	0x26, 0xba, 0x6b, 0xf7, 0x5c, 0x71, 0x37, 0xd8, 0x8e, 0x17, 0x3e, 0xf7, 0x01, 0x30, 0x63, 0x0b,
	0xc2, 0x86, 0x21, 0xbc, 0xbe, 0x9b, 0xb0, 0x22, 0x27, 0xb0, 0x70, 0xa9, 0x6c, 0x00, 0x8f, 0x91,
	0x85, 0x52, 0xf0, 0x4c, 0x87, 0x57, 0x42, 0xa5, 0x54, 0x3b, 0x2d, 0x63, 0xf8, 0x8b, 0xf5, 0xb0,
	0x61, 0xd9, 0xd9, 0x37, 0x8d, 0xc1, 0x2e, 0x36, 0x53, 0xf7, 0x27, 0x69, 0x9a, 0xb7, 0xf4, 0xd7,
	0x76, 0x60, 0x6b, 0x86, 0x2a, 0xe7, 0x22, 0x33, 0x4a, 0x77, 0x83, 0x45, 0x6a, 0xbf, 0x87, 0xcd,
	0x15, 0x01, 0x2f, 0xef, 0x17, 0x50, 0x6f, 0x5f, 0xcf, 0xd8, 0xfb, 0xd0, 0xf2, 0x07, 0x17, 0x66,
	0x5d, 0x2b, 0x28, 0x43, 0x7b, 0x07, 0xc8, 0xb5, 0xf3, 0xa0, 0x4d, 0x3a, 0x3b, 0x01, 0xb9, 0x2e,
	0xb3, 0xc2, 0x79, 0x58, 0x65, 0x85, 0xfb, 0x83, 0xc0, 0xd3, 0x06, 0x4a, 0xf1, 0x19, 0xd5, 0x78,
	0xff, 0x7a, 0x7d, 0x00, 0x69, 0x54, 0x84, 0x31, 0x16, 0xff, 0xe6, 0xf1, 0xcd, 0xad, 0xb2, 0xe4,
	0xd2, 0x80, 0x43, 0xb0, 0xca, 0xdb, 0x3c, 0xa3, 0xc9, 0x14, 0xcd, 0xba, 0x3b, 0x41, 0x79, 0xbd,
	0xbf, 0x94, 0xb9, 0xfb, 0xb9, 0x69, 0x9a, 0x8f, 0x45, 0x65, 0x66, 0xc3, 0x1a, 0xf2, 0xff, 0xd6,
	0x9c, 0x7d, 0x27, 0x70, 0xc4, 0x44, 0xba, 0x6e, 0xc6, 0xfc, 0xb9, 0x43, 0xf2, 0xf5, 0x5b, 0xc4,
	0xf5, 0x64, 0x3a, 0xf2, 0x98, 0x48, 0xbb, 0x93, 0x42, 0xa2, 0x4a, 0x70, 0x1c, 0xa1, 0xea, 0x52,
	0xc5, 0x31, 0x3f, 0xbe, 0x52, 0x34, 0xc5, 0xb9, 0x50, 0xf1, 0x71, 0x24, 0xba, 0xd5, 0xb8, 0x79,
	0x16, 0xea, 0x50, 0x2a, 0x9e, 0x72, 0xcd, 0x67, 0xd8, 0xbd, 0xf5, 0xe4, 0x84, 0x91, 0x08, 0x4d,
	0xf1, 0xd7, 0xc6, 0xe6, 0xe5, 0xe0, 0xa3, 0x3f, 0x3c, 0x1b, 0x6d, 0x9a, 0xfc, 0xcd, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x96, 0xb6, 0xb7, 0xa0, 0x04, 0x00, 0x00,
}
