// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ecdh1pu_aead.proto

package ecdh1pu_aead_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common_go_proto "github.com/google/tink/go/proto/common_go_proto"
	tink_go_proto "github.com/google/tink/go/proto/tink_go_proto"
	math "math"

	common_composite_go_proto "github.com/hyperledger/aries-framework-go/pkg/crypto/tinkcrypto/primitive/proto/common_composite_go_proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ecdh1PuKwParams struct {
	CurveType            common_go_proto.EllipticCurveType `protobuf:"varint,1,opt,name=curve_type,json=curveType,proto3,enum=google.crypto.tink.EllipticCurveType" json:"curve_type,omitempty"`
	KeyType              common_composite_go_proto.KeyType `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=google.crypto.tink.KeyType" json:"key_type,omitempty"`
	Recipients           []*Ecdh1PuAeadRecipientPublicKey  `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Ecdh1PuKwParams) Reset()         { *m = Ecdh1PuKwParams{} }
func (m *Ecdh1PuKwParams) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuKwParams) ProtoMessage()    {}
func (*Ecdh1PuKwParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{0}
}

func (m *Ecdh1PuKwParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuKwParams.Unmarshal(m, b)
}
func (m *Ecdh1PuKwParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuKwParams.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuKwParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuKwParams.Merge(m, src)
}
func (m *Ecdh1PuKwParams) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuKwParams.Size(m)
}
func (m *Ecdh1PuKwParams) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuKwParams.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuKwParams proto.InternalMessageInfo

func (m *Ecdh1PuKwParams) GetCurveType() common_go_proto.EllipticCurveType {
	if m != nil {
		return m.CurveType
	}
	return common_go_proto.EllipticCurveType_UNKNOWN_CURVE
}

func (m *Ecdh1PuKwParams) GetKeyType() common_composite_go_proto.KeyType {
	if m != nil {
		return m.KeyType
	}
	return common_composite_go_proto.KeyType_UNKNOWN_KEY_TYPE
}

func (m *Ecdh1PuKwParams) GetRecipients() []*Ecdh1PuAeadRecipientPublicKey {
	if m != nil {
		return m.Recipients
	}
	return nil
}

type Ecdh1PuAeadEncParams struct {
	AeadEnc              *tink_go_proto.KeyTemplate `protobuf:"bytes,1,opt,name=aead_enc,json=aeadEnc,proto3" json:"aead_enc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Ecdh1PuAeadEncParams) Reset()         { *m = Ecdh1PuAeadEncParams{} }
func (m *Ecdh1PuAeadEncParams) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadEncParams) ProtoMessage()    {}
func (*Ecdh1PuAeadEncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{1}
}

func (m *Ecdh1PuAeadEncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadEncParams.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadEncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadEncParams.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadEncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadEncParams.Merge(m, src)
}
func (m *Ecdh1PuAeadEncParams) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadEncParams.Size(m)
}
func (m *Ecdh1PuAeadEncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadEncParams.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadEncParams proto.InternalMessageInfo

func (m *Ecdh1PuAeadEncParams) GetAeadEnc() *tink_go_proto.KeyTemplate {
	if m != nil {
		return m.AeadEnc
	}
	return nil
}

type Ecdh1PuAeadParams struct {
	KwParams             *Ecdh1PuKwParams              `protobuf:"bytes,1,opt,name=kw_params,json=kwParams,proto3" json:"kw_params,omitempty"`
	EncParams            *Ecdh1PuAeadEncParams         `protobuf:"bytes,2,opt,name=enc_params,json=encParams,proto3" json:"enc_params,omitempty"`
	EcPointFormat        common_go_proto.EcPointFormat `protobuf:"varint,3,opt,name=ec_point_format,json=ecPointFormat,proto3,enum=google.crypto.tink.EcPointFormat" json:"ec_point_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Ecdh1PuAeadParams) Reset()         { *m = Ecdh1PuAeadParams{} }
func (m *Ecdh1PuAeadParams) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadParams) ProtoMessage()    {}
func (*Ecdh1PuAeadParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{2}
}

func (m *Ecdh1PuAeadParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadParams.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadParams.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadParams.Merge(m, src)
}
func (m *Ecdh1PuAeadParams) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadParams.Size(m)
}
func (m *Ecdh1PuAeadParams) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadParams.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadParams proto.InternalMessageInfo

func (m *Ecdh1PuAeadParams) GetKwParams() *Ecdh1PuKwParams {
	if m != nil {
		return m.KwParams
	}
	return nil
}

func (m *Ecdh1PuAeadParams) GetEncParams() *Ecdh1PuAeadEncParams {
	if m != nil {
		return m.EncParams
	}
	return nil
}

func (m *Ecdh1PuAeadParams) GetEcPointFormat() common_go_proto.EcPointFormat {
	if m != nil {
		return m.EcPointFormat
	}
	return common_go_proto.EcPointFormat_UNKNOWN_FORMAT
}

type Ecdh1PuAeadPublicKey struct {
	Version              uint32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params               *Ecdh1PuAeadParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	KID                  string             `protobuf:"bytes,3,opt,name=KID,proto3" json:"KID,omitempty"`
	X                    []byte             `protobuf:"bytes,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte             `protobuf:"bytes,5,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Ecdh1PuAeadPublicKey) Reset()         { *m = Ecdh1PuAeadPublicKey{} }
func (m *Ecdh1PuAeadPublicKey) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadPublicKey) ProtoMessage()    {}
func (*Ecdh1PuAeadPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{3}
}

func (m *Ecdh1PuAeadPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadPublicKey.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadPublicKey.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadPublicKey.Merge(m, src)
}
func (m *Ecdh1PuAeadPublicKey) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadPublicKey.Size(m)
}
func (m *Ecdh1PuAeadPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadPublicKey proto.InternalMessageInfo

func (m *Ecdh1PuAeadPublicKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ecdh1PuAeadPublicKey) GetParams() *Ecdh1PuAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Ecdh1PuAeadPublicKey) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func (m *Ecdh1PuAeadPublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Ecdh1PuAeadPublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type Ecdh1PuAeadPrivateKey struct {
	Version              uint32                `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PublicKey            *Ecdh1PuAeadPublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	KeyValue             []byte                `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Ecdh1PuAeadPrivateKey) Reset()         { *m = Ecdh1PuAeadPrivateKey{} }
func (m *Ecdh1PuAeadPrivateKey) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadPrivateKey) ProtoMessage()    {}
func (*Ecdh1PuAeadPrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{4}
}

func (m *Ecdh1PuAeadPrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadPrivateKey.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadPrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadPrivateKey.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadPrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadPrivateKey.Merge(m, src)
}
func (m *Ecdh1PuAeadPrivateKey) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadPrivateKey.Size(m)
}
func (m *Ecdh1PuAeadPrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadPrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadPrivateKey proto.InternalMessageInfo

func (m *Ecdh1PuAeadPrivateKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ecdh1PuAeadPrivateKey) GetPublicKey() *Ecdh1PuAeadPublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Ecdh1PuAeadPrivateKey) GetKeyValue() []byte {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type Ecdh1PuAeadRecipientPublicKey struct {
	Version              uint32                            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CurveType            common_go_proto.EllipticCurveType `protobuf:"varint,2,opt,name=curve_type,json=curveType,proto3,enum=google.crypto.tink.EllipticCurveType" json:"curve_type,omitempty"`
	KeyType              common_composite_go_proto.KeyType `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=google.crypto.tink.KeyType" json:"key_type,omitempty"`
	KID                  string                            `protobuf:"bytes,4,opt,name=KID,proto3" json:"KID,omitempty"`
	X                    []byte                            `protobuf:"bytes,5,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte                            `protobuf:"bytes,6,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Ecdh1PuAeadRecipientPublicKey) Reset()         { *m = Ecdh1PuAeadRecipientPublicKey{} }
func (m *Ecdh1PuAeadRecipientPublicKey) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadRecipientPublicKey) ProtoMessage()    {}
func (*Ecdh1PuAeadRecipientPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{5}
}

func (m *Ecdh1PuAeadRecipientPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadRecipientPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadRecipientPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey.Merge(m, src)
}
func (m *Ecdh1PuAeadRecipientPublicKey) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey.Size(m)
}
func (m *Ecdh1PuAeadRecipientPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadRecipientPublicKey proto.InternalMessageInfo

func (m *Ecdh1PuAeadRecipientPublicKey) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Ecdh1PuAeadRecipientPublicKey) GetCurveType() common_go_proto.EllipticCurveType {
	if m != nil {
		return m.CurveType
	}
	return common_go_proto.EllipticCurveType_UNKNOWN_CURVE
}

func (m *Ecdh1PuAeadRecipientPublicKey) GetKeyType() common_composite_go_proto.KeyType {
	if m != nil {
		return m.KeyType
	}
	return common_composite_go_proto.KeyType_UNKNOWN_KEY_TYPE
}

func (m *Ecdh1PuAeadRecipientPublicKey) GetKID() string {
	if m != nil {
		return m.KID
	}
	return ""
}

func (m *Ecdh1PuAeadRecipientPublicKey) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Ecdh1PuAeadRecipientPublicKey) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type Ecdh1PuAeadKeyFormat struct {
	Params               *Ecdh1PuAeadParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Ecdh1PuAeadKeyFormat) Reset()         { *m = Ecdh1PuAeadKeyFormat{} }
func (m *Ecdh1PuAeadKeyFormat) String() string { return proto.CompactTextString(m) }
func (*Ecdh1PuAeadKeyFormat) ProtoMessage()    {}
func (*Ecdh1PuAeadKeyFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77c865180c47e23, []int{6}
}

func (m *Ecdh1PuAeadKeyFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ecdh1PuAeadKeyFormat.Unmarshal(m, b)
}
func (m *Ecdh1PuAeadKeyFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ecdh1PuAeadKeyFormat.Marshal(b, m, deterministic)
}
func (m *Ecdh1PuAeadKeyFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ecdh1PuAeadKeyFormat.Merge(m, src)
}
func (m *Ecdh1PuAeadKeyFormat) XXX_Size() int {
	return xxx_messageInfo_Ecdh1PuAeadKeyFormat.Size(m)
}
func (m *Ecdh1PuAeadKeyFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_Ecdh1PuAeadKeyFormat.DiscardUnknown(m)
}

var xxx_messageInfo_Ecdh1PuAeadKeyFormat proto.InternalMessageInfo

func (m *Ecdh1PuAeadKeyFormat) GetParams() *Ecdh1PuAeadParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*Ecdh1PuKwParams)(nil), "google.crypto.tink.Ecdh1puKwParams")
	proto.RegisterType((*Ecdh1PuAeadEncParams)(nil), "google.crypto.tink.Ecdh1puAeadEncParams")
	proto.RegisterType((*Ecdh1PuAeadParams)(nil), "google.crypto.tink.Ecdh1puAeadParams")
	proto.RegisterType((*Ecdh1PuAeadPublicKey)(nil), "google.crypto.tink.Ecdh1puAeadPublicKey")
	proto.RegisterType((*Ecdh1PuAeadPrivateKey)(nil), "google.crypto.tink.Ecdh1puAeadPrivateKey")
	proto.RegisterType((*Ecdh1PuAeadRecipientPublicKey)(nil), "google.crypto.tink.Ecdh1puAeadRecipientPublicKey")
	proto.RegisterType((*Ecdh1PuAeadKeyFormat)(nil), "google.crypto.tink.Ecdh1puAeadKeyFormat")
}

func init() { proto.RegisterFile("proto/ecdh1pu_aead.proto", fileDescriptor_a77c865180c47e23) }

var fileDescriptor_a77c865180c47e23 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xce, 0xb4, 0x50, 0xe8, 0x03, 0x04, 0x37, 0x9a, 0x6c, 0x00, 0x23, 0xd6, 0x90, 0xf4, 0x42,
	0x1b, 0x30, 0xf1, 0x60, 0x62, 0xa2, 0x08, 0x12, 0xd2, 0xc4, 0xd4, 0x09, 0x7a, 0xf0, 0xb2, 0x19,
	0xa6, 0x8f, 0x65, 0xb2, 0x3f, 0x66, 0x32, 0x9d, 0x16, 0xf6, 0x7f, 0xf0, 0xee, 0xc9, 0x8b, 0x7f,
	0x9a, 0x89, 0x07, 0xff, 0x0b, 0xb3, 0x33, 0xbb, 0x75, 0x2b, 0xb5, 0xa8, 0xf1, 0x36, 0xef, 0xed,
	0x7b, 0xdf, 0x7e, 0xdf, 0x7b, 0xdf, 0x0c, 0xf8, 0x4a, 0x4b, 0x23, 0xbb, 0xc8, 0x07, 0x97, 0xfb,
	0x6a, 0x14, 0x30, 0x64, 0x83, 0x8e, 0x4d, 0x79, 0x5e, 0x28, 0x65, 0x18, 0x63, 0x87, 0xeb, 0x4c,
	0x19, 0xd9, 0x31, 0x22, 0x8d, 0x36, 0x3d, 0x57, 0xcd, 0x65, 0x92, 0xc8, 0xd4, 0xd5, 0x6d, 0x6e,
	0xb8, 0x5c, 0xfe, 0xbd, 0xc8, 0x6c, 0x57, 0xab, 0x02, 0x2e, 0x13, 0x25, 0x87, 0xc2, 0xa0, 0xfb,
	0xda, 0xfa, 0x4a, 0x60, 0xfd, 0xd8, 0xfd, 0xae, 0x77, 0xd5, 0x67, 0x9a, 0x25, 0x43, 0xef, 0x08,
	0x80, 0x8f, 0xf4, 0x18, 0x03, 0x93, 0x29, 0xf4, 0xc9, 0x0e, 0x69, 0xdf, 0x39, 0xd8, 0xed, 0xdc,
	0x24, 0xd0, 0x39, 0x8e, 0x63, 0xa1, 0x8c, 0xe0, 0xaf, 0xf2, 0xea, 0xb3, 0x4c, 0x21, 0x6d, 0xf2,
	0xf2, 0xe8, 0x3d, 0x85, 0xe5, 0x08, 0x33, 0x87, 0x51, 0xb3, 0x18, 0x5b, 0xb3, 0x30, 0x7a, 0x98,
	0xd9, 0xce, 0xa5, 0xc8, 0x1d, 0xbc, 0xb7, 0x00, 0x1a, 0xb9, 0x50, 0x02, 0x53, 0x33, 0xf4, 0xeb,
	0x3b, 0xf5, 0xf6, 0xca, 0xc1, 0xfe, 0xcc, 0xbf, 0x3b, 0xda, 0x2f, 0x91, 0x0d, 0x68, 0xd9, 0xd0,
	0x1f, 0x9d, 0xc7, 0x82, 0xf7, 0x30, 0xa3, 0x15, 0x90, 0x16, 0x85, 0x7b, 0x95, 0xe2, 0xe3, 0x94,
	0x17, 0x42, 0x9f, 0xc1, 0x72, 0x3e, 0xe2, 0x00, 0x53, 0x6e, 0x65, 0xae, 0x1c, 0x3c, 0xfc, 0x1d,
	0x45, 0x4c, 0x54, 0xcc, 0x0c, 0xd2, 0x25, 0xe6, 0x10, 0x5a, 0xdf, 0x09, 0xdc, 0xad, 0x80, 0x16,
	0x88, 0x2f, 0xa0, 0x19, 0x5d, 0x05, 0xca, 0x06, 0x05, 0xe4, 0xe3, 0x39, 0xdc, 0xcb, 0x91, 0xd3,
	0xe5, 0xa8, 0x1c, 0xfe, 0x09, 0x00, 0xa6, 0xbc, 0x84, 0xa8, 0x59, 0x88, 0xf6, 0x2d, 0xf2, 0x27,
	0x8a, 0x68, 0x13, 0x27, 0xe2, 0x4e, 0x61, 0x1d, 0x79, 0xa0, 0xa4, 0x48, 0x4d, 0x70, 0x21, 0x75,
	0xc2, 0x8c, 0x5f, 0xb7, 0x6b, 0x78, 0x34, 0x1b, 0xad, 0x9f, 0x57, 0xbe, 0xb6, 0x85, 0x74, 0x0d,
	0xab, 0x61, 0xeb, 0x33, 0x99, 0x1a, 0xe0, 0x64, 0xc8, 0x9e, 0x0f, 0x4b, 0x63, 0xd4, 0x43, 0x21,
	0x53, 0x2b, 0x76, 0x8d, 0x96, 0xa1, 0xf7, 0x1c, 0x1a, 0x53, 0x12, 0x76, 0x6f, 0x91, 0x50, 0xf0,
	0x2f, 0x9a, 0xbc, 0x0d, 0xa8, 0xf7, 0x4e, 0x8f, 0x2c, 0xe1, 0x26, 0xcd, 0x8f, 0xde, 0x2a, 0x90,
	0x6b, 0x7f, 0x61, 0x87, 0xb4, 0x57, 0x29, 0xb9, 0xce, 0xa3, 0xcc, 0x5f, 0x74, 0x51, 0xd6, 0xfa,
	0x44, 0xe0, 0x7e, 0x15, 0x4b, 0x8b, 0x31, 0x33, 0x38, 0x9f, 0xe0, 0x09, 0x80, 0xb2, 0x3a, 0x82,
	0x08, 0xb3, 0x3f, 0x9c, 0xf3, 0x4f, 0x77, 0x35, 0xd5, 0x64, 0x06, 0x5b, 0xd0, 0xcc, 0x7d, 0x3e,
	0x66, 0xf1, 0x08, 0x2d, 0xe1, 0x55, 0x9a, 0x1b, 0xff, 0x7d, 0x1e, 0xb7, 0xbe, 0x11, 0x78, 0x30,
	0xd7, 0xa7, 0x73, 0x18, 0x4e, 0x5f, 0xc3, 0xda, 0x7f, 0xb8, 0x86, 0xf5, 0xbf, 0xb8, 0x86, 0xc5,
	0x06, 0x16, 0x7e, 0xd9, 0xc0, 0xe2, 0xd4, 0x06, 0x1a, 0xe5, 0x06, 0xde, 0x4d, 0x19, 0xa4, 0x87,
	0x99, 0x73, 0x4e, 0xc5, 0x06, 0xe4, 0x1f, 0x6c, 0x70, 0xf8, 0x91, 0xc0, 0x36, 0x97, 0xc9, 0xac,
	0x26, 0xfb, 0x7c, 0xf5, 0xc9, 0x07, 0x16, 0x0a, 0x73, 0x39, 0x3a, 0xef, 0x70, 0x99, 0x74, 0x2f,
	0x33, 0x85, 0x3a, 0xc6, 0x41, 0x88, 0xba, 0xcb, 0xb4, 0xc0, 0xe1, 0xde, 0x85, 0x66, 0x09, 0x5e,
	0x49, 0x1d, 0xed, 0x85, 0xb2, 0xeb, 0xda, 0xed, 0xdb, 0x58, 0x1c, 0x95, 0x16, 0x89, 0x30, 0x62,
	0x8c, 0xdd, 0x9b, 0x0f, 0x6f, 0x10, 0xca, 0xc0, 0x66, 0xbf, 0xd4, 0x1a, 0x67, 0xa7, 0x6f, 0x7a,
	0xfd, 0xc3, 0xf3, 0x86, 0x8d, 0x9f, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x9b, 0xc2, 0x55,
	0xa7, 0x05, 0x00, 0x00,
}
