// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger/aries-framework-go/pkg/didcomm/messenger (interfaces: Provider)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	dispatcher "github.com/hyperledger/aries-framework-go/pkg/didcomm/dispatcher"
	reflect "reflect"
)

// MockProvider is a mock of Provider interface
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// OutboundDispatcher mocks base method
func (m *MockProvider) OutboundDispatcher() dispatcher.Outbound {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboundDispatcher")
	ret0, _ := ret[0].(dispatcher.Outbound)
	return ret0
}

// OutboundDispatcher indicates an expected call of OutboundDispatcher
func (mr *MockProviderMockRecorder) OutboundDispatcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboundDispatcher", reflect.TypeOf((*MockProvider)(nil).OutboundDispatcher))
}
